#
# Makefile for cclogic device.
#

obj-$(CONFIG_CCLOGIC)		    += cclogic-core.o
obj-$(CONFIG_CCLOGIC)               += cclogic-class.o
obj-$(CONFIG_TYPEC_CCLOGIC_PI5USB)  += pi5usb30216.o
obj-$(CONFIG_TYPEC_CCLOGIC_TUSB320) += tusb320.o
obj-$(CONFIG_TYPEC_CCLOGIC_TUSB320HAI) += tusb320hai.o
obj-$(CONFIG_TYPEC_CCLOGIC_PTN5150H) += ptn5150h.o
obj-$(CONFIG_TYPEC_CCLOGIC_PI5USBD)  += pi5usb30216d.o

