#
# Makefile for cclogic device.
#

obj-$(CONFIG_CCLOGIC)		    += cclogic-core.o
obj-$(CONFIG_CCLOGIC)               += cclogic-class.o
obj-$(CONFIG_TYPEC_CCLOGIC_TUSB320HAI) += tusb320hai.o
obj-$(CONFIG_TYPEC_CCLOGIC_PI5USBD)  += pi5usb30216d.o

