#!/bin/bash
export ARCH=arm64
export SUBARCH=arm64
export CROSS_COMPILE=aarch64-linux-gnu-

z2_plus(){
export KBUILD_BUILD_USER="z2_plus"
export KBUILD_BUILD_HOST="LibXZR"
make O=out mrproper&&make O=out z2_plus_defconfig&&make O=out -j16

cp -f out/arch/arm64/boot/Image.gz-dtb ~/AnyKernel2
cd ~/AnyKernel2
git checkout z2_plus_treble
zip -r "(z2_plus)Nameless Kernel[OC] Rx.zip" *
cp -f "(z2_plus)Nameless Kernel[OC] Rx.zip" ~
rm -f "(z2_plus)Nameless Kernel[OC] Rx.zip"

}

z2_plus

