#!/bin/bash
export ARCH=arm64
export SUBARCH=arm64
export CLANG_PATH="${HOME}/linux-x86/clang-r346389b"
export CROSS_COMPILE="${HOME}/aarch64-linux-android-4.9/bin/aarch64-linux-android-"
#export CROSS_COMPILE="${HOME}/gcc-arm-8.2-2018.11-x86_64-aarch64-linux-gnu/bin/aarch64-linux-gnu-"
export CC="$CLANG_PATH/bin/clang"
export CLANG_TRIPLE="aarch64-linux-gnu-"
export KBUILD_COMPILER_STRING=$($CLANG_PATH/bin/clang --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g' -e 's/[[:space:]]*$//')
z2_plus(){
export KBUILD_BUILD_USER="z2_plus"
export KBUILD_BUILD_HOST="LibXZR"
make O=out z2_plus_defconfig&&make O=out -j8
makezip
}


z2_row(){
export KBUILD_BUILD_USER="z2_row"
export KBUILD_BUILD_HOST="LibXZR"
make O=out z2_row_defconfig&&make O=out -j8
makezip
}

makezip(){
cp -f out/arch/arm64/boot/Image.gz-dtb ~/AnyKernel2
cd ~/AnyKernel2
git checkout 4.4-eas
zip -r "$zipname" *
cp -f "$zipname" ~
rm -f "$zipname"
}

clean(){
make mrproper
make O=out mrproper
}

if [ "$1" == z2_plus ]
then
zipname="(z2_plus)Nameless Kernel[4.4-EAS] Rx.zip"
ziped=0
if [ "$2" == "mkzip" ]
then
makezip
ziped=1
fi

if [ "$2" == "menu" ]
then
make O=out z2_plus_defconfig
make O=out menuconfig
ziped=1
fi

if [ "$2" == "save" ]
then
make O=out savedefconfig
ziped=1
fi

if [ "$2" == "regen" ]
then
make O=out z2_plus_defconfig
make O=out savedefconfig
mv out/defconfig arch/arm64/configs/z2_plus_defconfig
ziped=1
fi

if [ "$2" == "dirty" ]
then
z2_plus
else
if [ $ziped == 0 ]
then
clean
z2_plus
fi
fi

fi

if [ "$1" == z2_row ]
then
zipname="(z2_row)Nameless Kernel[4.4-EAS] Rx.zip"
ziped=0
if [ "$2" == "mkzip" ]
then
makezip
ziped=1
fi

if [ "$2" == "menu" ]
then
make O=out z2_row_defconfig
make O=out menuconfig
ziped=1
fi

if [ "$2" == "save" ]
then
make O=out savedefconfig
ziped=1
fi

if [ "$2" == "regen" ]
then
make O=out z2_row_defconfig
make O=out savedefconfig
mv out/defconfig arch/arm64/configs/z2_row_defconfig
ziped=1
fi

if [ "$2" == "dirty" ]
then
z2_row
else
if [ $ziped == 0 ]
then
clean
z2_row
fi
fi
fi

