#!/bin/bash
export ARCH=arm64
export SUBARCH=arm64
export CROSS_COMPILE=aarch64-linux-gnu-
zipname="(z2_pro)Nameless Kernel[Non-treble] Rx.zip"
z2_row(){
export KBUILD_BUILD_USER="z2_row"
export KBUILD_BUILD_HOST="LibXZR"
make O=out mrproper&&make O=out z2_row_defconfig&&make O=out -j16

cp -f out/arch/arm64/boot/Image.gz-dtb ~/AnyKernel2
cd ~/AnyKernel2
git checkout z2_plus_non-treble
zip -r "$zipname" *
cp -f "$zipname" ~
rm -f "$zipname"
}

z2_row
