ccflags-y += -Idrivers/media/platform/msm/camera_v2z
ccflags-y += -Idrivers/media/platform/msm/camera_v2z/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2z/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2z/common
obj-$(CONFIG_MSM_CPP) += msm_cpp_soc.o msm_cpp.o
