obj-$(CONFIG_GT1151_TOUCHPANEL_DRIVER)	+= gt1x.o
obj-$(CONFIG_GT1151_TOUCHPANEL_EXTENTS)	+= gt1x_extents.o
obj-$(CONFIG_GT1151_TOUCHPANEL_GENERIC)	+= gt1x_generic.o
obj-$(CONFIG_GT1151_TOUCHPANEL_UPDATE)	+= gt1x_update.o
obj-$(CONFIG_GT1151_TOUCHPANEL_TOOL)	+= gt1x_tools.o
#obj-y	+= gt1x.o
#obj-y	+= gt1x_extents.o
#obj-y	+= gt1x_generic.o
#obj-y	+= gt1x_update.o
#obj-y	+= gt1x_tools.o

