ccflags-y += -Idrivers/media/platform/msm/camera_v2z
ccflags-y += -Idrivers/media/platform/msm/camera_v2z/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2z/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2z/sensor/cci
obj-$(CONFIG_ZUK_CAMERA) += msm_actuator.o
