#gt915 touchpanel driver


obj-$(CONFIG_GT9X_V24_TOUCHPANEL_DRIVER)	+= gt9xx.o
#gt915 update file
obj-$(CONFIG_GT9X_V24_TOUCHPANEL_UPDATE)	+= gt9xx_update.o
#debug tool
obj-$(CONFIG_GT9X_V24_TOUCHPANEL_DEBUG)	+= goodix_tool.o
