ccflags-y += -Idrivers/media/platform/msm/camera_v2z/
ccflags-y += -Idrivers/media/platform/msm/camera_v2z/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2z/sensor
ccflags-y += -Idrivers/media/platform/msm/camera_v2z/sensor/cci
obj-$(CONFIG_ZUK_CAMERA)   += msm_camera_cci_i2c.o msm_camera_qup_i2c.o msm_camera_spi.o msm_camera_dt_util.o
